-- Schema for integration tests

DROP TABLE IF EXISTS CERTIFICATES;
DROP TABLE IF EXISTS TEMPLATE_VERSIONS;
DROP TABLE IF EXISTS TEMPLATES;
DROP TABLE IF EXISTS USERS;
DROP TABLE IF EXISTS CUSTOMERS;

CREATE TABLE CUSTOMERS (
    ID IDENTITY PRIMARY KEY,
    NAME VARCHAR(255) NOT NULL,
    EMAIL VARCHAR(255) UNIQUE NOT NULL,
    API_KEY VARCHAR(255) UNIQUE,
    API_SECRET VARCHAR(255),
    ACTIVE BOOLEAN DEFAULT TRUE,
    CREATED_AT TIMESTAMP NOT NULL,
    UPDATED_AT TIMESTAMP NOT NULL
);

CREATE TABLE USERS (
    ID IDENTITY PRIMARY KEY,
    CUSTOMER_ID BIGINT NOT NULL,
    USERNAME VARCHAR(255) UNIQUE NOT NULL,
    EMAIL VARCHAR(255) UNIQUE NOT NULL,
    PASSWORD VARCHAR(255),
    ROLE VARCHAR(50) NOT NULL,
    ACTIVE BOOLEAN DEFAULT TRUE,
    CREATED_AT TIMESTAMP NOT NULL,
    UPDATED_AT TIMESTAMP NOT NULL,
    FOREIGN KEY (CUSTOMER_ID) REFERENCES CUSTOMERS(ID)
);

CREATE TABLE TEMPLATES (
    ID IDENTITY PRIMARY KEY,
    CUSTOMER_ID BIGINT NOT NULL,
    NAME VARCHAR(255) NOT NULL,
    DESCRIPTION VARCHAR(4000),
    ACTIVE BOOLEAN DEFAULT TRUE,
    CREATED_AT TIMESTAMP NOT NULL,
    UPDATED_AT TIMESTAMP NOT NULL,
    FOREIGN KEY (CUSTOMER_ID) REFERENCES CUSTOMERS(ID)
);

CREATE TABLE TEMPLATE_VERSIONS (
    ID IDENTITY PRIMARY KEY,
    TEMPLATE_ID BIGINT NOT NULL,
    CUSTOMER_ID BIGINT NOT NULL,
    VERSION_NUMBER INTEGER NOT NULL,
    JSON_SCHEMA VARCHAR(4000) NOT NULL,
    TEMPLATE_CONTENT VARCHAR(4000),
    IMMUTABLE BOOLEAN DEFAULT TRUE,
    CREATED_AT TIMESTAMP NOT NULL,
    FOREIGN KEY (TEMPLATE_ID) REFERENCES TEMPLATES(ID),
    FOREIGN KEY (CUSTOMER_ID) REFERENCES CUSTOMERS(ID),
    UNIQUE (TEMPLATE_ID, VERSION_NUMBER)
);

CREATE TABLE CERTIFICATES (
    ID IDENTITY PRIMARY KEY,
    CUSTOMER_ID BIGINT NOT NULL,
    TEMPLATE_ID BIGINT NOT NULL,
    TEMPLATE_VERSION_ID BIGINT NOT NULL,
    CERTIFICATE_DATA VARCHAR(4000),
    PDF_URL VARCHAR(500),
    HASH VARCHAR(255),
    SIGNATURE VARCHAR(255),
    STATUS VARCHAR(50) NOT NULL,
    CREATED_AT TIMESTAMP NOT NULL,
    UPDATED_AT TIMESTAMP NOT NULL,
    FOREIGN KEY (CUSTOMER_ID) REFERENCES CUSTOMERS(ID),
    FOREIGN KEY (TEMPLATE_ID) REFERENCES TEMPLATES(ID),
    FOREIGN KEY (TEMPLATE_VERSION_ID) REFERENCES TEMPLATE_VERSIONS(ID)
);
